classification: tool
color: ''
description_extra: ''
description_main: ''
id: tool_drill_hammer_18_volt_dewalt_tower_dewalt_dc988
manufacturer: dewalt
part_number: dc988
size: 18_volt_dewalt_tower
type: drill_hammer
