classification: tool
color: ''
description_extra: ''
description_main: ''
id: tool_vibratory_bowl_tabletop_mettler_toledo_lv11
manufacturer: mettler_toledo
part_number: lv11
size: tabletop
type: vibratory_bowl
