classification: tool
color: ''
description_extra: ''
description_main: 200_gram_capacity
id: tool_scale_76_mm_width_114_mm_height_20_mm_depth_200_gram_capacity_aliexpress_jewelry_scale
manufacturer: aliexpress
part_number: jewelry_scale
size: 76_mm_width_114_mm_height_20_mm_depth
type: scale
