classification: tool
color: ''
description_extra: ''
description_main: ''
id: tool_drill_hammer_18_volt_ryobi_one_ryobi_r18pd3
manufacturer: ryobi
part_number: r18pd3
size: 18_volt_ryobi_one
type: drill_hammer
