classification: tool
color: ''
description_extra: 2_mm
description_main: hex_head
id: tool_screw_driver_bit_quarter_inch_drive_100_mm_depth_hex_head_2_mm
manufacturer: ''
part_number: ''
size: quarter_inch_drive_100_mm_depth
type: screw_driver_bit
